//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp_Assignment.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_assign
    {
        public string Name { get; set; }
        [Required(ErrorMessage ="Required")]
        public string FamilyName { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Required")]
        public string City { get; set; }
        [Required(ErrorMessage = "Required")]
        [MinLength(6, ErrorMessage ="Cant less than 6")]
        public string ZipCode { get; set; }
        [Required(ErrorMessage = "Required")]
        [MinLength(12, ErrorMessage ="Cant be less than 12 with country code")]
        public string  Phone { get; set; }
        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string Email { get; set; }

    }
}
